// SPDX-License-Identifier: MIT
// sport_tx_sync_nopll.v --- PLL-FREE, PRBS-31 source-synchronous to_dsp streamer.
//
// The DSP is the bus master: it drives the bit clock (fwd_aclk = the forwarded
// DSP SCLK). The FPGA never generates a clock (no PLL). The to_dsp payload is
// PRBS-31 (x^31 + x^28 + 1, seed 0x7FFFFFFF, MSB-first) generated by an LFSR
// that is STEPPED BY fwd_aclk. The DSP's RX LFSR starts from the same seed and
// is stepped by the same clock, so the two run in lockstep bit-for-bit with NO
// sync mechanism -- the receiver just compares against its own LFSR.
//
// No free-running anything, no dummy/idle/pattern startup, no frame recovery:
// the LFSR sits at its seed until the DSP's clock appears, then streams from
// word 0. afs marks bit0 of each 32-bit word for the DSP's late-FS framing.
//
// Output timing (kept from the counter version, which gave slips=0): the data
// and frame-sync are launched on the NEGEDGE via matched SB_IO output flops --
// a half-bit from from_dsp's posedge sample (SSO dodge) -- and aclk_out is a
// DDR output that rises at the posedge (centre of the DSP's data eye).

module sport_tx_sync_nopll #(
      parameter DATA_NEG = 1,
      parameter CLK_POS  = 1
   )(
      input  fwd_aclk,
      input  run,
      output ad0_out,
      output aclk_out,
      output afs_out
   );
   // Criteria: LFSR held at seed while RUN inactive; word zero is the
   // first FS after RUN goes active.
   reg [1:0] run_s = 2'b00;
   reg [5:0] warm  = 6'd0;   // stable-clock ticks after RUN before word 0
   localparam [30:0] PRBS31_SEED = 31'h7FFFFFFF;

   reg [30:0] lfsr   = PRBS31_SEED;
   reg [4:0]  bitcnt = 5'd0;
   reg        ad0_p  = 1'b0;
   reg        afs_p  = 1'b0;

   // One PRBS bit per forwarded-aclk period, MSB-first, afs on bit0 of a word.
   always @(posedge fwd_aclk) begin
      run_s <= {run_s[0], run};
      if (!run_s[1] || warm != 6'd63) begin
         if (run_s[1])
            warm <= warm + 6'd1;
         else
            warm <= 6'd0;
         lfsr   <= PRBS31_SEED;
         bitcnt <= 5'd0;
         ad0_p  <= 1'b0;
         afs_p  <= 1'b0;
      end else begin
      // next PRBS bit = lfsr[30] ^ lfsr[27]  (x^31 + x^28 + 1)
      ad0_p  <= lfsr[30] ^ lfsr[27];
      afs_p  <= (bitcnt == 5'd0);
      lfsr   <= {lfsr[29:0], (lfsr[30] ^ lfsr[27])};
      bitcnt <= bitcnt + 5'd1;   // wraps 31->0 naturally
      end
   end

   // Phase knobs swept to centre the DSP's sample point in the data eye:
   //   DATA_NEG: launch data/afs on the negedge (1) or posedge (0) of fwd_aclk.
   //   CLK_POS:  forwarded clock rises at posedge (1) or negedge (0).
   SB_IO #(.PIN_TYPE(6'b010100), .NEG_TRIGGER(DATA_NEG ? 1'b1 : 1'b0)) ad0_io (
      .PACKAGE_PIN(ad0_out), .OUTPUT_CLK(fwd_aclk), .D_OUT_0(ad0_p)
   );
   SB_IO #(.PIN_TYPE(6'b010100), .NEG_TRIGGER(DATA_NEG ? 1'b1 : 1'b0)) afs_io (
      .PACKAGE_PIN(afs_out), .OUTPUT_CLK(fwd_aclk), .D_OUT_0(afs_p)
   );
   SB_IO #(.PIN_TYPE(6'b010000)) aclk_io (
      .PACKAGE_PIN(aclk_out), .OUTPUT_CLK(fwd_aclk),
      .D_OUT_0(CLK_POS ? 1'b1 : 1'b0), .D_OUT_1(CLK_POS ? 1'b0 : 1'b1)
   );
endmodule
